### ISSUE TITLE
Roadmap to 0.0.1

### ISSUE THREAD

**Issue by angusmoore** [angusmoore/RSDSGE.jl#7]
This is a list of tasks that I want to complete before I register the first version of RSDSGE.jl with Julia's package manager.

I will add links to issues and open pull requests for these tasks as appropriate.

- [ ] Cleaning up code. Currently much of the code is quick and dirty.
    * Split files in logical places and reorder into sensible folders.
    * Add type annotations to function definitions to ensure clarity of API.
- [ ] Documentation and examples.
    * Docstrings for exported functions.
- [x] API to allow models to be declared in text files, rather than in arrays.
- [ ] Better than 90% test coverage.
